LL-238
luminosityleds/server pull request #72
Opened 2023-10-28 06:02 UTC by KevinLemon112

# Description

Ticket creates the RabbitMQ management service using the files in the src/notification folder of the LL repo. Files created: devcontainer.json, connection.js/connection.ts, docker-cmpose.yaml, rabbitmq-data. 

Subsequent # (issue)

LL-238

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

The way I verified my changes worked was to create a queue, send messages to the queue in the RabbitMQ management hub, and get the messages from there and make sure they sent. The steps are as follows:

1. Open VSCode and Docker Desktop

2. Be in the LL-238 directory (or the master if the ticket is already pushed) and then cd into the src/notification directory where are the files are located

3. Run and install the following if they are not already: 
       -npm install amqplib -S
       -npm install @types/amqplib -D
       -npm install --save-dev @types/amqplib @types/node 

4. Run: 
       -docker-compose up -d
       -followed by: node connection.js

4.5: if errors occur, try running tsc connection.ts and then doing the above again. OR trying running docker-compose up -d again OR restart VSCode and Docker Desktop and try again

5. go to the local host: http://localhost:15672/ (open it in a browser)

6. You should see a login page, the username and password are in the environment part of the docker-compose.yaml file

7. Click queues -> myQueue -> "Get messages" drop down menu (insert "11" where it says "Messages: ") -> get messages button

8. Should see "Hello, RabbitMQ!" message along with "message 0", "message 1", ... until 9

9. If all works, you would have successfully made the RabbitMQ connection, sent messages to RabbitMQ, and let RabbitMQ consume your messages in the queue which you can now view

# Checklist (when relevant):

- [x] My code follows the style guidelines of this project

    [TypeScript](https://google.github.io/styleguide/tsguide.html)
[Python](https://peps.python.org/pep-0008/)
[Schema](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/forefront-2010/ee652242(v=vs.100))
- [x] I have included a reviewer on the pull request [Reviewer #1: @pogi7, Reviewer #2: @erikajledesma ]
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-11-03 16:16 UTC, pogi7 requested changes
@KevinLemon112 

I'm getting the following error:
```typescript
 ~/gi/p/server/sr/notification  LL-238 <4 *2 !1 ?1  docker compose up -d           INT  41s  09:14:24 AM 
[+] Building 0.0s (0/0)                                                                     docker:colima
[+] Running 1/1
 ✔ Container rabbitmq  Started                                                                       0.0s 

 ~/gi/p/server/sr/notification  LL-238 <4 *2 !1 ?1  node connection.js                   ok  09:14:27 AM 
Error connecting to RabbitMQ: Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5672
}

2023-12-29 06:59 UTC, pogi7 commented on src/notification/publish/package.json
> +    "publish": "npx ts-node publish.ts"
@KevinLemon112 The reason why the publish notification service wasn't working previously was there was no `npx ts-node` that is required to compile and run typescript code.

2023-12-29 06:59 UTC, pogi7 commented on src/notification/subscribe/package.json
> +    "subscribe": "npx ts-node subscribe.ts"
@KevinLemon112 The reason why the subscribe notification service wasn't working previously was there was no `npx ts-node` that is required to compile and run typescript code.

2024-01-11 06:01 UTC, pogi7 approved these changes
i'm approving, but @KevinLemon112 make a new ticket to fix the unit test that's not working

2024-01-12 04:59 UTC, erikajledesma approved these changes
looks goodd

2024-01-12 05:01 UTC, merged